CREATE TABLE IF NOT EXISTS fact_player_game_logs ( 
    season_year TEXT,
    player_id BIGINT,
    player_name TEXT,
    team_id BIGINT,
    team_abbreviation TEXT,
    game_id TEXT,
    game_date DATE,
    matchup TEXT,
    wl TEXT,
    minutes NUMERIC,
    points INTEGER,
    rebounds INTEGER,
    assists INTEGER,
    steals INTEGER,
    blocks INTEGER,
    turnovers INTEGER,
    field_goals_made INTEGER,
    field_goals_attempted INTEGER,
    field_goal_pct NUMERIC,
    three_pointers_made INTEGER,
    three_pointers_attempted INTEGER,
    three_point_pct NUMERIC,
    free_throws_made INTEGER,
    free_throws_attempted INTEGER,
    free_throw_pct NUMERIC,
    plus_minus NUMERIC

);
